version: '3'

services:

  postgres:
    image: 'postgres:15'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: go_cms
